### ISSUE TITLE
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.i s_available() is False. If you are running on a CPU-only machine, please use tor ch.load with map_location='cpu' to map your storages to the CPU.

### ISSUE THREAD

**Issue by MarlNox** [kamalkraj/BERT-NER#27]
Hello guys, 

Anytime I try to run the script, I get this error. 

Any suggestions on how to fix it?

(base) C:\Users\user1\Desktop\BERT-NER-experiment>activate neuro

(neuro) C:\Users\user1\Desktop\BERT-NER-experiment>python
Python 3.6.8 |Anaconda, Inc.| (default, Feb 21 2019, 18:30:04) [MSC v.1916 64 bi
t (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from bert import Ner
Better speed can be achieved with apex installed from https://www.github.com/nvi
dia/apex.
>>> model = Ner("out_!x/")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\user1\Desktop\BERT-NER-experiment\bert.py", line 35, in __ini
t__
    self.model , self.tokenizer, self.model_config = self.load_model(model_dir)
  File "C:\Users\user1\Desktop\BERT-NER-experiment\bert.py", line 48, in load_
model
    model.load_state_dict(torch.load(output_model_file))
  File "C:\Users\user1\Anaconda3\envs\neuro\lib\site-packages\torch\serializat
ion.py", line 387, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\user1\Anaconda3\envs\neuro\lib\site-packages\torch\serializat
ion.py", line 574, in _load
    result = unpickler.load()
  File "C:\Users\user1\Anaconda3\envs\neuro\lib\site-packages\torch\serializat
ion.py", line 537, in persistent_load
    deserialized_objects[root_key] = restore_location(obj, location)
  File "C:\Users\user1\Anaconda3\envs\neuro\lib\site-packages\torch\serializat
ion.py", line 119, in default_restore_location
    result = fn(storage, location)
  File "C:\Users\user1\Anaconda3\envs\neuro\lib\site-packages\torch\serializat
ion.py", line 95, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "C:\Users\user1\Anaconda3\envs\neuro\lib\site-packages\torch\serializat
ion.py", line 79, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.i
s_available() is False. If you are running on a CPU-only machine, please use tor
ch.load with map_location='cpu' to map your storages to the CPU.
>>>
>>> output = model.predict("Steve went to Paris")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'model' is not defined

**Comment by kamalkraj** [comment]
Hi @MarlNox ,
Fixed model loading on `cpu` 
pull the latest commit and try
