### ISSUE TITLE
FP16 not working!

### ISSUE THREAD

**Issue by 0x01h** [kamalkraj/BERT-NER#41]
When I pass --fp16 parameter to train faster, it gives the following error:
```python
Traceback (most recent call last):                                                                                              | 0/1 [00:00<?, ?it/s]
  File "run_ner.py", line 594, in <module>
    main()
  File "run_ner.py", line 487, in main
    loss = model(input_ids, segment_ids, input_mask, label_ids,valid_ids,l_mask)
  File "/root/miniconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "run_ner.py", line 46, in forward
    logits = self.classifier(sequence_output)
  File "/root/miniconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/miniconda3/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 87, in forward
    return F.linear(input, self.weight, self.bias)
  File "/root/miniconda3/lib/python3.6/site-packages/torch/nn/functional.py", line 1371, in linear
    output = input.matmul(weight.t())
RuntimeError: Expected object of scalar type Float but got scalar type Half for argument #2 'mat2'
```

**Comment by 0x01h** [comment]
Why did you close this issue without any explanation or improvement? @kamalkraj

**Comment by kamalkraj** [comment]
Hi @0x01h ,
Fixed in the default branch `dev`
BERT-BASE , 1 Epoch result
```
              precision    recall  f1-score   support
        LOC     0.9185    0.9257    0.9221      1668
       MISC     0.7457    0.8020    0.7728       702
        ORG     0.8622    0.8892    0.8755      1661
        PER     0.9609    0.9586    0.9598      1617

avg / total     0.8926    0.9090    0.9006      5648
```

**Comment by 0x01h** [comment]
Thank you!
