### ISSUE TITLE
out_!x

### ISSUE THREAD

**Issue by jx669** [kamalkraj/BERT-NER#81]
when I am on _Deploy REST-API_, it returns this:

```
Traceback (most recent call last):
  File "api.py", line 9, in <module>
    model = Ner("out_!x")
  File "/home/name/BERT-NER/bert.py", line 34, in __init__
    self.model , self.tokenizer, self.model_config = self.load_model(model_dir)
  File "/home/name/BERT-NER/bert.py", line 44, in load_model
    model_config = json.load(open(model_config))
FileNotFoundError: [Errno 2] No such file or directory: 'out_!x/model_config.json'
```
ubuntu
my directory is the same as the original. base and cpp-app are placed at the same level.
-base
-api.py
-cpp-app

is "out_!x" a typo? or does it have special reference? 

i went to the file model_config.json, it does not have "label_map", but in the class Ner, the initialization goes:

` self.model , self.tokenizer, self.model_config = self.load_model(model_dir)
        self.label_map = self.model_config["label_map"]
        self.max_seq_length = self.model_config["max_seq_length"]
        self.label_map = {int(k):v for k,v in self.label_map.items()}
`

Anyway, there seems to be some naming/conventional inconsistencies in the code related to _Deploy REST-API_ section. Could you check that?

**Comment by jx669** [comment]
For later viewers, I should have downloaded "out_base" model. 

Under Result section, there are two models. The first one is named "out_base" (trained with bert-base), and the second one is named "base" (trained with bert_large). 

If you download "out_base" and placed in the top level, you should be fine with one change in api.py. Change "out_x!" to "out_base", then it will all work.
