### ISSUE TITLE
Ner("out_!x")

### ISSUE THREAD

**Issue by jx669** [kamalkraj/BERT-NER#82]
As I am just exploring, I did not install all the requirements. 
I am more interested in inference in production. 
Till the section _Inference C++_, the code works fine. But when I am on _Deploy REST-API_, it returns this:

```
Traceback (most recent call last):
  File "api.py", line 9, in <module>
    model = Ner("out_!x")
  File "/home/name/BERT-NER/bert.py", line 34, in __init__
    self.model , self.tokenizer, self.model_config = self.load_model(model_dir)
  File "/home/name/BERT-NER/bert.py", line 44, in load_model
    model_config = json.load(open(model_config))
FileNotFoundError: [Errno 2] No such file or directory: 'out_!x/model_config.json'
```
ubuntu
directory:
-base
-api.py
-cpp-app
is "out_!x" a typo? or does it have special reference? Thanks!

**Comment by jx669** [comment]
just noticed I accidentally posted twice.
