### ISSUE TITLE
KeyError: ''

### ISSUE THREAD

**Issue by Rajmehta123** [kamalkraj/BERT-NER#87]
@kamalkraj

I am training the model on a custom dataset and even before training starts, I get the error as:

`Traceback (most recent call last):
  File "run_ner.py", line 594, in <module>
    main()
  File "run_ner.py", line 464, in main
    train_examples, label_list, args.max_seq_length, tokenizer)
  File "run_ner.py", line 210, in convert_examples_to_features
    label_ids.append(label_map[labels[i]])
KeyError: ''`

Tracing the error, I assume the error is coming from the dataset where one of the sentences is blank, i.e.:

each sentence is separated by 2 newlines, i.e.: '\n\n'
`1990 I-TIME\nto O\ncarry O\nout O\na O\nfriendly O\nofficial O\nvisit O\n. O\n\nThe O\npicture O\nshowed O\nPremier O\nPeng B-PERSON`
Above example, sentences are separated by '\n\n'.

```
def get_labels(self):
        return ["O", "B-ADDR", "I-ADDR", "I-QUANTITY", "I-PRODUCT", "B-PERCENT", "B-GPE", "B-PERSON", "I-MONEY", "B-ORDINAL", "I-ORG", "B-QUANTITY", "B-LANGUAGE", "I-TIME", "I-ORDINAL", "I-LANGUAGE", "I-LAW", "B-CARDINAL", "B-WORK_OF_ART", "B-EVENT", "I-WORK_OF_ART", "B-DATE", "I-NORP", "I-CARDINAL", "B-PRODUCT", "I-GPE", "I-FAC", "B-TIME", "I-LOC", "B-MONEY", "B-LAW", "I-EVENT", "B-FAC", "B-NORP", "I-PERCENT", "I-PERSON", "B-LOC", "B-ORG", "I-DATE", "[CLS]", "[SEP]"]

```
I changed the labels to include all the tags the data set contains.

Now when I include `''` in the get_labels, it fixes the error.

Any idea what is the error?

I have attached a sample valid and test file.

[test.txt](https://github.com/kamalkraj/BERT-NER/files/4669527/test.txt)
[valid.txt](https://github.com/kamalkraj/BERT-NER/files/4669530/valid.txt)

**Comment by Rajmehta123** [comment]
I fixed it. My dataset did not have 2 new lines at the end of the file. Hence, it was expecting some blank token with a blank tag, hence keyerror: ''.
